routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get("/", function() {
    return view("landingpage");
});


Auth::routes();

// Inventory Routes

Route::get('/inventory/create', [App\Http\Controllers\InventoriesController::class, 'create']);
Route::post('/inventory', [App\Http\Controllers\InventoriesController::class, 'store']);
Route::get('/inventory/{id}', [App\Http\Controllers\InventoriesController::class, 'show']);

// Resource Routes

Route::resource('resource', \App\Http\Controllers\ResourcesController::class);

Route::get('/profile/{user}', [App\Http\Controllers\ProfilController::class, 'index'])->name('profile.show');

app/Models/Inventory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Inventory extends Model
{
    use HasFactory;

    protected $fillable = [
        'name', 'description', 'thumbnail'
    ];


    public function inventory() {
        return $this->belongsTo("\App\Models\User");
    }

    public function resources() {
        return $this->hasMany("\App\Models\Resource");
    }

}

app/Models/Resource.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Resource extends Model
{
    use HasFactory;

    protected $fillable = [
        'product', 'manufacturer', 'info', 'price'
    ];

    public function inventory() {
        return $this->belongsTo("\App\Models\Inventory");
    }

}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name',
        'username',
        'bar',
        'email',
        'password',
    ];

    

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function inventory() {
        return $this->hasOne("\App\Models\Inventory");
    }

}

app/Http/Controllers/BarController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Inventory;

class BarController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index($inventory)
    {

        $inventory = Inventory::findOrFail($inventory);

        return view('bar.bar', ["inventory" => $inventory]);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/InventoriesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Inventory;

class InventoriesController extends Controller
{

    public function __construct() {
        $this->middleware('auth');
    }

    public function create() {
        return view('bar.create');
    }

    public function store() {

        $input = request()->validate([
            'name'=>'required',
            'description'=>'required',
            'thumbnail'=>'image'
        ]);

        $imageUrl = "";

        if(isset($input->thumbnail)) {
            $imageUrl = request()->thumbnail->store('uploads', 'public');
        }


        auth()->user()->inventory()->create([
            'name' => $input['name'],
            'description' => $input['description'],
            'thumbnail' => $imageUrl,
        ]);
        
        return redirect('/inventory/' . auth()->user()->inventory->id);
    }

    public function show($id) {
        $inventory = Inventory::findOrFail($id);

        return view('bar.bar', ["inventory" => $inventory]);
    }
}

app/Http/Controllers/ProfilController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\User;

class ProfilController extends Controller
{

    public function index($user)
    {
        $user = User::findOrFail($user);

        return view('user.profile', [
            'user' => $user,
        ]);
    }
}

app/Http/Controllers/ResourcesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use \App\Models\Resource;

class ResourcesController extends Controller
{
    
    public function __construct() {
        $this->middleware('auth');
    }

    public function create() {
        return view('bar.resources.add');
    }

    public function store() {

        $input = request()->validate([
            'product'=>'required',
            'manufacturer'=>'required',
            'info'=>'',
            'price'=>'numeric'
        ]);

        auth()->user()->inventory->resources()->create($input);

        return redirect("inventory/".auth()->user()->inventory->id);
    }

    public function edit(Resource $resource)
    {
        return view('bar.resources.edit', compact('resource'));
    }

    public function update(Request $request, Resource $resource) {


        $input = $request->validate([
            'product'=>'required',
            'manufacturer'=>'required',
            'info'=>'',
            'price'=>'numeric'
        ]);

        $resource->update($input);
        return redirect("inventory/".auth()->user()->inventory->id);
    }

    public function destroy($id) {
        \App\Models\Resource::find($id)->delete();
        return \App::make('redirect')->back()->with('flash_success');
    }

}

resources/views/bar/bar.blade.php
@extends("layouts.app")

@section("content")

<div class="container mt-5">
    <div class="row">
        <div class="col-md-4">
            <img src="/storage/{{ $inventory->thumbnail }}" style="width: 250px" />
        </div>
        <div class="col-md-8 pt-5">
            <h2 class="mt-3">{{ $inventory->name }}</h2>
            <p class="lead">{{ $inventory->description }}</p>
        </div>
    </div>
    <div class="row mt-3">
        <div class="alert alert-secondary w-100">
            <div class="d-flex justify-content-between">
                <a class="btn btn-success" href="{{ url('/resource/create') }}">Add Item</a>
                <button class="btn btn-success">Filter</button>
            </div>
        </div>
    </div>
    <div class="row">
        <table class="table">
            <thead class="thead-dark">
                <tr>
                <th scope="col">#</th>
                <th scope="col">Produkt</th>
                <th scope="col">Marke</th>
                <th scope="col">Info</th>
                <th scope="col">Preis</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach($inventory->resources as $item)
                <tr>
                    <th scope="row">{{ $loop->index + 1 }}</th>
                    <td>{{ $item->product}}</td>
                    <td>{{$item->manufacturer}}</td>
                    <td>{{$item->info}}</td>
                    <td>{{$item->price.' €'}}</td>
                    <td>
                        <form action="{{ url('/resource', ['id' => $item->id]) }}" method="post">
                            <a href="{{ route('resource.edit', $item->id) }}" class="btn btn-primary">Edit</a>
                            <input class="btn btn-danger" type="submit" value="X" />
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>

@endsection

resources/views/bar/create.blade.php
@extends('layouts.app')

@section('content')

<div class="container mt-5">
    <form action="/inventory" enctype="multipart/form-data" method="post">
        @csrf
        <div class="row">
            <div class="col-8 offset-2">
            
                <div class="row">
                    <h1>Inventar erstellen</h1>
                </div>

                <div class="form-group row">
                    <label for="name" class="col-md-4 col-form-label">Inventar-Name </label>

                        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ old('name') }}" required autocomplete="name" autofocus>

                        @error('name')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="description" class="col-md-4 col-form-label">Beschreibung</label>

                        <textarea id="description" type="text" class="form-control @error('description') is-invalid @enderror" name="description" value="{{ old('description') }}" required >
                        </textarea>

                        @error('description')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="row">
                    <label for="thumbnail" class="col-md-4 col-form-label">Thumbnail</label>
                    <input type="file" class="form-control-file" id="thumbnail" name="thumbnail">
                    @error('thumbnail')
                        <span class="invalid-feedback" role="alert">
                            <strong>{{ $message }}</strong>
                        </span>
                    @enderror
                </div>
                <div class="row mt-3">
                    <button class="btn btn-primary">Erstellen</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/bar/resources/add.blade.php
@extends("layouts.app")

@section("content")

<div class="container mt-5">
    <form action="/resource" enctype="multipart/form-data" method="post">
        @csrf
        <div class="row">
            <div class="col-8 offset-2">
            
                <div class="row">
                    <h1>Item hinzufügen</h1>
                </div>

                <div class="form-group row">
                    <label for="product" class="col-md-4 col-form-label">Item Name</label>

                        <input id="product" type="text" class="form-control @error('product') is-invalid @enderror" name="product" value="{{ old('product') }}" required>

                        @error('product')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="manufacturer" class="col-md-4 col-form-label">Hersteller</label>

                        <input id="manufacturer" type="text" class="form-control @error('manufacturer') is-invalid @enderror" name="manufacturer" value="{{ old('manufacturer') }}" required>

                        @error('manufacturer')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label">Preis</label>

                        <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ old('price') }}" required>

                        @error('price')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="info" class="col-md-4 col-form-label">Zusätzliche Infos</label>

                        <textarea id="info" type="text" class="form-control @error('info') is-invalid @enderror" name="info" value="{{ old('info') }}" required >
                        </textarea>

                        @error('info')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="row mt-3">
                    <button class="btn btn-primary">Erstellen</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/bar/resources/edit.blade.php
@extends("layouts.app")

@section("content")

<div class="container mt-5">
    <form action="{{ route('resource.update',$resource->id) }}" enctype="multipart/form-data" method="post">
        @csrf
        @method('put')
        <div class="row">
            <div class="col-8 offset-2">
            
                <div class="row">
                    <h1>Item bearbeiten</h1>
                </div>

                <div class="form-group row">
                    <label for="product" class="col-md-4 col-form-label">Item Name</label>

                        <input id="product" type="text" class="form-control @error('product') is-invalid @enderror" name="product" value="{{ $resource->product }}" required>

                        @error('product')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="manufacturer" class="col-md-4 col-form-label">Hersteller</label>

                        <input id="manufacturer" type="text" class="form-control @error('manufacturer') is-invalid @enderror" name="manufacturer" value="{{ $resource->manufacturer }}" required>

                        @error('manufacturer')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="price" class="col-md-4 col-form-label">Preis</label>

                        <input id="price" type="text" class="form-control @error('price') is-invalid @enderror" name="price" value="{{ $resource->price }}" required>

                        @error('price')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="form-group row">
                    <label for="info" class="col-md-4 col-form-label">Zusätzliche Infos</label>

                        <textarea id="info" type="text" class="form-control @error('info') is-invalid @enderror" name="info" value="{{ $resource->info }}" required >
                            {{ $resource->info }}
                        </textarea>

                        @error('info')
                            <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                        @enderror
                </div>

                <div class="row mt-3">
                    <button class="btn btn-success">Aktualisieren</button>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection

resources/views/landingpage.blade.php
@extends('layouts.app')

@section('content')
<div class="jumbotron hero">
        <div class="container text-center text-light p-5">
            <h1 class="display-2">Barkeep</h1>
            <p class="lead text-light">Barkeep ist dein virtuelles Lager. Deine Bar. Dein Inventar. Mit Barkeep behälst du deinen Bestand ganz einfach im Überblick.</p>
            <p>
            @if (Route::has('login'))
                    <div class="hidden fixed top-0 right-0 px-6 py-4 sm:block">
                        @auth
                            <a href="{{ url('/home') }}" class="btn btn-outline-light">Home</a>
                        @else
                            <a href="{{ route('login') }}" class="text-sm text-gray-700 underline">Login</a>

                            @if (Route::has('register'))
                                <a href="{{ route('register') }}" class="ml-4 text-sm text-gray-700 underline">Register</a>
                            @endif
                        @endif
                    </div>
                @endif
            </p>
        </div>
    </div>
    <br>
    <div class="container marketing text-center">
    <div class="row">
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p class="lead">Donec sed odio dui. Etiam porta sem malesuada magna mollis euismod. Nullam id dolor id nibh ultricies vehicula ut id elit. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Praesent commodo cursus magna.</p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p class="lead">Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Cras mattis consectetur purus sit amet fermentum. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
          <div class="col-lg-4">
            <img class="rounded-circle mb-2" src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Generic placeholder image" width="140" height="140">
            <h2>Heading</h2>
            <p class="lead">Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
            <p><a class="btn btn-primary" href="#" role="button">View details &raquo;</a></p>
          </div><!-- /.col-lg-4 -->
        </div><!-- /.row -->
    </div>
    <div class="container mt-4">
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="img/feature.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-fluid mx-auto" src="img/feature.jpg" alt="Generic placeholder image">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
          <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
        </div>
      </div>
    </div>

@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Barkeep</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">

            <a class="navbar-brand d-flex align-items-center" href="{{ url('/') }}">
                <div>
                    <img src="/img/cocktail-solid.svg" style="height: 23px;" class="pr-2" />
                </div>
                <div class="pl-2">
                    Barkeep
                </div>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                <span class="navbar-toggler-icon"></span>
            </button>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <!-- Left Side Of Navbar -->
                <ul class="navbar-nav mr-auto">

                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="navbar-nav ml-auto">
                    <!-- Authentication Links -->
                    @guest
                        @if (Route::has('login'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                        @endif
                        
                        @if (Route::has('register'))
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                            </li>
                        @endif
                    @else
                        <li class="nav-item">
                            <a class="nav-link" href="{{ url('/') }}">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->name }}
                            </a>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                @if(Auth::user()->inventory != null)
                                    <a href="{{ url('inventory/'.Auth::user()->inventory->id) }}" class="dropdown-item">
                                        Bar
                                    </a>
                                @else
                                    <a href="{{ url('/inventory/create') }}" class="dropdown-item">
                                        Bar
                                    </a>
                                @endif
                                <a href="{{ url('profile/'.Auth::user()->id) }}" class="dropdown-item">
                                    Profil
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                    onclick="event.preventDefault();
                                                    document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                    @csrf
                                </form>
                            </div>
                        </li>
                    @endguest
                </ul>
                </div>
        </nav>

        <main>
            @yield('content')
            <footer class="container">
                <hr>
                <p class="float-right"><a href="#">Back to top</a></p>
                <p>&copy; 2020 Barkeep GmbH &middot; <a href="#">Impressum</a> &middot; <a href="#">AGB</a></p>
            </footer>
        </main>
    </div>
</body>
</html>

resources/views/user/profile.blade.php
@extends("layouts.app")

@section("content")

<!-- From https://bootsnipp.com/snippets/K0ZmK  -->

<div class="container emp-profile">
    <form method="post">
        <div class="row">
            <div class="col-md-4">
                <div class="profile-img">
                    <img src="/img/profile.png" alt=""/>
                </div>
            </div>
            <div class="col-md-6">
                <div class="profile-head">
                            <h5>
                                {{ $user->name }}
                            </h5>
                            <h6>
                                {{ $user->bar }}
                            </h6>
                            <br>
                    <ul class="nav nav-tabs" id="myTab" role="tablist">
                        <li class="nav-item">
                            <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="true">About</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-2">
                <input type="submit" class="profile-edit-btn" name="btnAddMore" value="Edit Profile"/>
            </div>
        </div>
        <div class="row">
            <div class="col-md-4">
            </div>
            <div class="col-md-8">
                <div class="tab-content profile-tab" id="myTabContent">
                    <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Benutzername</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ $user->username }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Bar</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ $user->bar }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Email</label>
                                    </div>
                                    <div class="col-md-6">
                                        <p>{{ $user->email }}</p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <label>Inventar</label>
                                    </div>
                                    <div class="col-md-6">
                                            <p>
                                                
                                                @if($user->inventory != null)
                                                    <a href="{{ url('/inventory/'. $user->inventory->id) }}">
                                                    {{ $user->inventory->name }}</a>
                                                @else
                                                    <a href="{{ url('/inventory/create') }}">Inventar erstellen</a>
                                                @endif

                                             </p>
                                    </div>
                                </div>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@endsection